.PHONY: clean All

All:
	@echo "----------Building project:[ UOCBurgLib - Debug ]----------"
	@cd "UOCBurgLib" && "$(MAKE)" -f  "UOCBurgLib.mk"
	@echo "----------Building project:[ UOCBurgApp - Debug ]----------"
	@cd "UOCBurgApp" && "$(MAKE)" -f  "UOCBurgApp.mk"
clean:
	@echo "----------Cleaning project:[ UOCBurgLib - Debug ]----------"
	@cd "UOCBurgLib" && "$(MAKE)" -f  "UOCBurgLib.mk"  clean
	@echo "----------Cleaning project:[ UOCBurgApp - Debug ]----------"
	@cd "UOCBurgApp" && "$(MAKE)" -f  "UOCBurgApp.mk" clean
